### ISSUE TITLE
Examples not loading

### ISSUE THREAD

**Issue by cam** [tshaddix/oocharts-js#1]
I've loaded the examples into a folder on my server, along with the js, but the js doesn't seem to load properly. Are the example files relevant to the new API?

Testing location: http://cam.vc/oocharts/timeline.html

**Comment by cam** [comment]
Blurgh! Yep. My Profile ID was not set in the code. That's something to watch out for, as it isn't made 100% clear to look out for it in the documentation.

**Comment by tshaddix** [comment]
@Cam thanks for pointing this out! I will update documentation.

**Comment by cam** [comment]
No problem! Thanks for the great app. My testing is going really well so far :) Is the Google group the best place to ask questions?

**Comment by tshaddix** [comment]
Awesome! I'm always happy to hear our products actually work (kidding) ;)

Feel free to post issues or questions here, and we will be happy to help out. Also (because I know you were one of the first users of the script), we released a couple new versions today that fix a variety of bugs people ran in to, so you may want to download the new version of the script and replace your current one just so you don't have any of those same issues.

Also, I added a line to the documentation instructing users to replace the lines you mentioned above with their information. Thanks for all the help!

**Comment by cam** [comment]
Haha! It works beautifully :)

Great! I am keen to be an active participant. Thanks for the heads up. I will grab a copy of the new version, and start playing!

Thank you!
