### ISSUE TITLE
OOcharts takes too long to load charts

### ISSUE THREAD

**Issue by radaniba** [tshaddix/oocharts-js#36]
I am using javascript to display different charts (even one) but I figured out that it takes too long to load charts (more than 6 seconds)

Any idea on how to optimize loading time ?

Thanks

**Comment by tshaddix** [comment]
There is not much we can do on our end that we're not already doing. We cache requests for an hour, so after the first request, any matching request for the next hour is responded to almost immediately as we don't need to talk to Google's servers.

If it's too slow for you, you may want to run a server side script to pull data every hour or so and store that somewhere. Then you can just pull from your own server rather than OOcharts from your JS script.
